#!/usr/bin/env bash
# fork from https://gist.github.com/jakemhiller/d342ad51505addf78ec628a16fd3280f

changed_files="$(git diff-tree -r --name-only --no-commit-id $1 $2)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

check_run package.json "npm prune && npm install"
check_run bower.json "bower prune && bower install"
